### ISSUE TITLE
Key Error while using limiting reagent function.

### ISSUE THREAD

**Issue by KevinDenzil** [harirakul/chemlib#13]
While using the limiting reagent function, 
terminal cites line 337 :  data = [a[-1][mode.capitalize()] for a in eq_amounts]
and shows : KeyError: 'Grams'

This is code where it is used:
 if eventlr == 'Apply':
                                x=int(float(valueslr['R1']))
                                y=int(float(valueslr['R2']))
                                lr = rxn.limiting_reagent(x, y, mode = type)
                                winlr('lr').Update(value=lr.formula)

It is a program made using pysimplegui and chemlib
type is a string variable (grams,moles or molecules)
and x and y are integers

Please Help

**Comment by harirakul** [comment]
Thanks for pointing this out! The error was in the .capitalize() part - I removed that and it works.

**Comment by KevinDenzil** [comment]
> Thanks for pointing this out! The error was in the .capitalize() part - I removed that and it works.

Thank you so much!
it works now!
